badge:
    resource: "@BadgeBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
user_bundle:
   resource: "@UserBundle/Resources/config/routing.yml"
# src/OC/PlatformBundle/Resources/config/routing.yml

